### ISSUE TITLE
investigate panic in TestDeleteService

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#346]
```
Ilkers-MacBook-Pro:core ilgooz$ go test ./...
ok  	github.com/mesg-foundation/core/api	2.148s
ok  	github.com/mesg-foundation/core/api/client	0.858s
--- FAIL: TestDeleteService (0.00s)
panic: resource temporarily unavailable [recovered]
	panic: resource temporarily unavailable

goroutine 21 [running]:
testing.tRunner.func1(0xc4204560f0)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:742 +0x29d
panic(0x1684260, 0x1acd668)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/mesg-foundation/core/database/services.open(0x0, 0x17ca740, 0x1acd668)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/database/services/db.go:23 +0x19d
github.com/mesg-foundation/core/database/services.Save(0xc4203265f0, 0x0, 0x0, 0x0, 0x0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/database/services/save.go:14 +0x97
github.com/mesg-foundation/core/api/core.(*Server).DeployService(0x1b340c8, 0x17d0840, 0xc4200220a8, 0xc420039598, 0xc4203bfa88, 0x2d2, 0x10f11c0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/api/core/deploy.go:12 +0x32
github.com/mesg-foundation/core/api/core.TestDeleteService(0xc4204560f0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/api/core/delete_test.go:24 +0x1d4
testing.tRunner(0xc4204560f0, 0x1775b50)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/mesg-foundation/core/api/core	0.554s

```

**Comment by antho1404** [comment]
may be related to https://github.com/mesg-foundation/core/issues/354

**Comment by NicolasMahe** [comment]
This bug didn't appear for long and the related issue #354 has been closed.
Closing this issue as well.
