### ISSUE TITLE
leveldb: resource temporarily unavailable

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#389]
happened to me during go testing interface/grc in https://github.com/mesg-foundation/core/pull/383

```
--- FAIL: TestSubmit (13.64s)
panic: resource temporarily unavailable [recovered]
	panic: resource temporarily unavailable

goroutine 149 [running]:
testing.tRunner.func1(0xc4203621e0)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:742 +0x29d
panic(0x188af20, 0x1ea37a8)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/mesg-foundation/core/database/services.open(0x0, 0x1a33c80, 0x1ea37a8)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/database/services/db.go:23 +0x19d
github.com/mesg-foundation/core/database/services.Get(0xc420410390, 0x23, 0xc42037c740, 0x0, 0xc420034b0c, 0x4, 0xc4204108a0, 0x28, 0xc4201c59b0, 0x0, ...)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/database/services/get.go:10 +0x6b
github.com/mesg-foundation/core/api.(*serviceDeleter).Delete(0xc420303db0, 0xc420410390, 0x23, 0xc4203ce1e0, 0xc42048a1a8)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/api/delete_deleter.go:19 +0x8c
github.com/mesg-foundation/core/api.(*API).DeleteService(0xc420242048, 0xc420410390, 0x23, 0x0, 0x0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/api/delete.go:5 +0x49
github.com/mesg-foundation/core/interface/grpc/service.TestSubmit(0xc4203621e0)
	/Users/ilgooz/Programs/go/src/github.com/mesg-foundation/core/interface/grpc/service/submit_result_test.go:66 +0x713
testing.tRunner(0xc4203621e0, 0x19c5748)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/mesg-foundation/core/interface/grpc/service	14.409s

```

**Comment by ilgooz** [comment]
i've solved this by deleting _$HOME/.mesg/database_
