### ISSUE TITLE
grpc goaway

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#760]
happened after ~2 days run of marketplace service on DO droplet

```
root@marketplace-service:~# docker service logs core-5ecd2e15230cff43bb7529942c221505605f9e52-service
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.k9sjv9cpmjop@marketplace-service    | 
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.k9sjv9cpmjop@marketplace-service    | > service-ethereum@1.0.0 start /app
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.k9sjv9cpmjop@marketplace-service    | > ts-node src/index.ts
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.k9sjv9cpmjop@marketplace-service    | 
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    | 
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    | > service-ethereum@1.0.0 start /app
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    | > ts-node src/index.ts
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    | 
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    | catch listenTask { Error: 13 INTERNAL: GOAWAY received
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at ClientReadableStream._emitStatusIfDone (/app/node_modules/grpc/src/client.js:233:26)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at ClientReadableStream._receiveStatus (/app/node_modules/grpc/src/client.js:211:8)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1272:15)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |     at /app/node_modules/grpc/src/client_interceptors.js:1029:24
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |   code: 13,
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |   metadata: Metadata { _internal_repr: {} },
core-5ecd2e15230cff43bb7529942c221505605f9e52-service.1.ym2qexlzf1hz@marketplace-service    |   details: 'GOAWAY received' }
```

**Comment by NicolasMahe** [comment]
Seems like the client is spamming the core?

**Comment by ilgooz** [comment]
@NicolasMahe this is likely because of that. We need to increase keepAlive to maybe 5mins

**Comment by NicolasMahe** [comment]
I think I find the reason.
```
// EnforcementPolicy is used to set keepalive enforcement policy on the
// server-side. Server will close connection with a client that violates this
// policy.
type EnforcementPolicy struct {
	// MinTime is the minimum amount of time a client should wait before sending
	// a keepalive ping.
	MinTime time.Duration // The current default value is 5 minutes.
	// If true, server allows keepalive pings even when there are no active
	// streams(RPCs). If false, and client sends ping when there are no active
	// streams, server will send GOAWAY and close the connection.
	PermitWithoutStream bool // false by default.
}
```
https://github.com/grpc/grpc-go/blob/master/keepalive/keepalive.go

The client should not ping more often that this `MinTime`.

**Comment by NicolasMahe** [comment]
I make some test with a client in go (easier to configure) with a Time of 1 second and I get the error `transport is closing` on client and `context canceled` on server.

**Comment by ilgooz** [comment]
I'm running the marketplace service from the v0.8 for a few days. I haven't got the error again yet.

**Comment by NicolasMahe** [comment]
> I'm running the marketplace service from the v0.8 for a few days. I haven't got the error again yet.

Ok good. I run some test and the `GOAWAY` error is **only** when the client spam the server.
If the server spam the client, I don't get any error.. (even without touching `EnforcementPolicy.MinTime`).

**Comment by NicolasMahe** [comment]
PR https://github.com/mesg-foundation/core/pull/774 is fixing this issue.
